services:
  # Combined Service (Backend + Frontend)
  - type: web
    name: agent-sterling
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      # API routes first
      - type: rewrite
        source: /api/*
        destination: /api/$1
      # Static file routes
      - type: rewrite
        source: /static/*
        destination: /static/$1
      - type: rewrite
        source: /*.js
        destination: /app.js
      - type: rewrite
        source: /*.css
        destination: /styles.css
      - type: rewrite
        source: /*.jpg
        destination: /sterling.jpg
      - type: rewrite
        source: /health
        destination: /api/health
      # SPA fallback
      - type: rewrite
        source: /*
        destination: /index.html 