services:
  # Backend API Service
  - type: web
    name: agent-sterling-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000

  # Static Frontend Service
  - type: static
    name: agent-sterling-static
    buildCommand: echo "Static files ready"
    staticPublishPath: ./static
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 