services:
  # Combined Service (Backend + Frontend)
  - type: web
    name: agent-sterling
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /static/*
        destination: /static/$1
      - type: rewrite
        source: /health
        destination: /health
      - type: rewrite
        source: /*.(js|css|jpg|png|ico)
        destination: /$1
      - type: rewrite
        source: /*
        destination: /index.html 