services:
  # Backend Service
  - type: web
    name: agent-sterling-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/data
    startCommand: python -m uvicorn src.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ENVIRONMENT
        value: production
      - key: DATA_DIR
        value: /opt/render/project/src/data
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Service
  - type: static
    name: agent-sterling-frontend
    buildCommand: |
      mkdir -p dist
      cp -r static/* dist/
    staticPublishPath: ./dist
    autoDeploy: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"